from pathlib import Path

def patch(path, replacements):
    p=Path(path); s=p.read_text()
    for old,new in replacements:
        if old not in s: raise SystemExit(f'marker not found in {path}: {old[:100]!r}')
        s=s.replace(old,new,1)
    p.write_text(s)

patch('internal/panel/handlers.go', [
 ('\t\tConfigJSON:     cfgJSON,\n\t\tHotspot: HotspotSpec{','''\t\tConfigJSON: cfgJSON,\n\t\tUpstream: UpstreamProxySpec{\n\t\t\tEnabled: st.Advanced.UpstreamEnabled, Host: st.Advanced.UpstreamHost,\n\t\t\tPort: st.Advanced.UpstreamPort, Username: st.Advanced.UpstreamUsername.Reveal(),\n\t\t\tPassword: st.Advanced.UpstreamPassword.Reveal(),\n\t\t},\n\t\tHotspot: HotspotSpec{'''),
 ('\tonLAN := r.PostFormValue("panel_on_lan") == "1"\n\tconnectionsOnly := r.PostFormValue("connections_only") == "1"\n','''\tonLAN := r.PostFormValue("panel_on_lan") == "1"\n\tconnectionsOnly := r.PostFormValue("connections_only") == "1"\n\tupstreamEnabled := r.PostFormValue("upstream_enabled") == "1"\n\tupstreamHost := strings.TrimSpace(r.PostFormValue("upstream_host"))\n\tupstreamUsername := strings.TrimSpace(r.PostFormValue("upstream_username"))\n\tupstreamPassword := r.PostFormValue("upstream_password")\n\tupstreamPort := uint16(0)\n\tif v := strings.TrimSpace(r.PostFormValue("upstream_port")); v != "" {\n\t\tn, e := strconv.ParseUint(v, 10, 16)\n\t\tif e != nil || n == 0 { sess.setFlash(Problem{Headline: MsgSaveAdvancedFailed, Advice: MsgSaveFailedAdvice}, ""); p.home(w,r); return }\n\t\tupstreamPort = uint16(n)\n\t}\n\tif upstreamEnabled && (upstreamHost == "" || upstreamPort == 0 || strings.ContainsAny(upstreamHost, " \\t\\r\\n")) {\n\t\tsess.setFlash(Problem{Headline: MsgSaveAdvancedFailed, Advice: MsgSaveFailedAdvice}, ""); p.home(w,r); return\n\t}\n'''),
 ('\t\tst.Advanced.PanelOnLAN = onLAN\n\t\treturn nil\n','''\t\tst.Advanced.PanelOnLAN = onLAN\n\t\tst.Advanced.UpstreamEnabled = upstreamEnabled\n\t\tst.Advanced.UpstreamHost = upstreamHost\n\t\tst.Advanced.UpstreamPort = upstreamPort\n\t\tst.Advanced.UpstreamUsername = state.Secret(upstreamUsername)\n\t\tif upstreamPassword != "" { st.Advanced.UpstreamPassword = state.Secret(upstreamPassword) }\n\t\treturn nil\n''')])

patch('internal/panel/view.go', [
 ('\tPanelOnLAN    bool\n\tConfigFacts   []Fact\n','''\tPanelOnLAN       bool\n\tUpstreamEnabled  bool\n\tUpstreamHost     LTR\n\tUpstreamPort     LTR\n\tUpstreamUsername string\n\tConfigFacts      []Fact\n'''),
 ('\td.CurrentInternet = LTR(adv.InternetInterface)\n\td.CurrentHotspot = LTR(adv.HotspotInterface)\n','''\td.CurrentInternet = LTR(adv.InternetInterface)\n\td.CurrentHotspot = LTR(adv.HotspotInterface)\n\td.UpstreamEnabled = adv.UpstreamEnabled\n\td.UpstreamHost = LTR(adv.UpstreamHost)\n\tif adv.UpstreamPort != 0 { d.UpstreamPort = LTR(strconv.Itoa(int(adv.UpstreamPort))) }\n\td.UpstreamUsername = adv.UpstreamUsername.Reveal()\n''')])

p=Path('internal/panel/templates/index.html'); s=p.read_text()
marker='      <button type="submit" class="go">{{.T "advanced.save"}}</button>'
block='''      <fieldset class="upstream-box">\n        <legend>{{if eq .Dir "rtl"}}پراکسی بالادستی SOCKS5{{else}}Upstream SOCKS5 proxy{{end}}</legend>\n        <p class="hint">{{if eq .Dir "rtl"}}اختیاری است؛ ترافیک کاسپین ابتدا به این SOCKS5 می‌رود و نیازی به VLESS یا VMess جداگانه نیست.{{else}}Optional; Caspian sends traffic to this SOCKS5 first. No separate VLESS or VMess configuration is required.{{end}}</p>\n        <label><input type="checkbox" name="upstream_enabled" value="1" {{if .UpstreamEnabled}}checked{{end}}> {{if eq .Dir "rtl"}}استفاده از پراکسی بالادستی{{else}}Use upstream proxy{{end}}</label>\n        <label for="upstream_host">{{if eq .Dir "rtl"}}آدرس / IP پراکسی{{else}}Proxy address / IP{{end}}</label>\n        <input id="upstream_host" name="upstream_host" type="text" value="{{.UpstreamHost}}" dir="ltr" autocomplete="off" spellcheck="false">\n        <label for="upstream_port">{{if eq .Dir "rtl"}}پورت{{else}}Port{{end}}</label>\n        <input id="upstream_port" name="upstream_port" type="number" min="1" max="65535" value="{{.UpstreamPort}}" dir="ltr">\n        <label for="upstream_username">{{if eq .Dir "rtl"}}نام کاربری (اختیاری){{else}}Username (optional){{end}}</label>\n        <input id="upstream_username" name="upstream_username" type="text" value="{{.UpstreamUsername}}" dir="ltr" autocomplete="off">\n        <label for="upstream_password">{{if eq .Dir "rtl"}}رمز عبور (اختیاری){{else}}Password (optional){{end}}</label>\n        <input id="upstream_password" name="upstream_password" type="password" value="" dir="ltr" autocomplete="new-password">\n        <p class="hint">{{if eq .Dir "rtl"}}اگر رمز قبلی تنظیم شده و این کادر خالی باشد، رمز قبلی حفظ می‌شود.{{else}}If a password is already set and this field is empty, the existing password is kept.{{end}}</p>\n      </fieldset>\n\n'''+marker
if marker not in s: raise SystemExit('advanced template marker not found')
p.write_text(s.replace(marker,block,1))
print('panel patch applied')
